default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Trek5200 # Password updated after forgetting it multiple times :) 
  host: localhost

development:
  <<: *default
  database: jbps_development

test:
  <<: *default
  database: jbps_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>